---
- hosts: localhost
  become: yes
  tasks:
    - name: Add GCP public key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add gcloud SDK repository
      apt_repository:
        repo: "deb http://packages.cloud.google.com/apt cloud-sdk-{{ ansible_distribution_release }} main"
        update_cache: yes

    - name: Install Google Cloud SDK
      apt:
        name: google-cloud-sdk
        state: latest

    - name: Install apache-libcloud for GCE modules
      pip:
        name: apache-libcloud
        state: latest

    - name: Important information
      debug:
        msg: "Don't forget to run 'gcloud init' to initialize SDK step-by-step"
