---
- name: 12-Deploying the DNS Cluster Add-on
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Deploying the DNS Cluster Add-on
      shell: kubectl apply -f https://storage.googleapis.com/kubernetes-the-hard-way/coredns.yaml
    - name: Pause and wait while DNS cluster is up
      pause:
        seconds: 15
    - name: Start container to verify everything works
      shell: kubectl run busybox --image=busybox:1.28 --command -- sleep 3600
