---
- name: 12-Deploying the DNS Cluster Add-on
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Deploying the DNS Cluster Add-on
      shell: "{{ item }}"
      with_items:
        - "kubectl apply -f https://storage.googleapis.com/kubernetes-the-hard-way/coredns.yaml"
        - "kubectl run busybox --image=busybox:1.28 --command -- sleep 3600"
