---
- name: Clean Up GCP resources to save money
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Delete controller and worker compute instances
      gcp_compute_instance:
        project: "{{ project_id }}"
        zone: europe-west1-b
        state: absent
        name: "{{ item }}"
      with_items:
        - controller-0
        - controller-1
        - controller-2
        - worker-0
        - worker-1
        - worker-2

    - name: Delete forwarding rule
      gcp_compute_forwarding_rule:
        project: "{{ project_id }}"
        region: europe-west1
        name: kubernetes-forwarding-rule
        state: absent

    - name: Delete target pool
      gcp_compute_target_pool:
        project: "{{ project_id }}"
        region: europe-west1
        name: kubernetes-target-pool
        state: absent

    - name: Delete HTTP health check
      gcp_compute_http_health_check:
        project: "{{ project_id }}"
        name: kubernetes
        state: absent

    - name: Delete Static External IP address
      gcp_compute_address:
        project: "{{ project_id }}"
        region: europe-west1
        name: kubernetes-the-hard-way 
        state: absent

    - name: Delete firewall rules
      gcp_compute_firewall:
        project: "{{ project_id }}"
        name: "{{ item }}"
        state: absent
      with_items:
        - kubernetes-the-hard-way-allow-internal
        - kubernetes-the-hard-way-allow-external
        - kubernetes-the-hard-way-allow-health-check

    - name: Delete network routes
      gcp_compute_route:
        project: "{{ project_id }}"
        name: "kubernetes-route-10-200-{{ item }}-0-24"
        dest_range: "10.200.{{ item }}.0/24"
        network:
          selfLink: "projects/{{ project_id }}/global/networks/kubernetes-the-hard-way" 
        state: absent
      with_items:
        - 0
        - 1
        - 2
    
    - name: Delete subnetwork
      gcp_compute_subnetwork:
        project: "{{ project_id }}"
        network:
          selfLink: "projects/{{ project_id }}/global/networks/kubernetes-the-hard-way" 
        ip_cidr_range: 10.240.0.0/24
        region: europe-west1
        state: absent
        name: kubernetes

    - name: Delete VPC network
      gcp_compute_network:
        project: "{{ project_id }}"
        state: absent
        name: kubernetes-the-hard-way
 
    - name: Delete local directory with configs and keys
      become: yes
      file:
        path: /opt/kubernetes-pki/
        state: absent
