---

# install client tools (cfssl, cfssljson and kubectl)
- import_playbook: 02-client-tools.yml

# provision compute resources
- import_playbook: 03-compute-resources.yml
- import_playbook: additional-tasks/03-1-gather-facts.yml

# provision a Certificate Authority and generate TLS certificates
- import_playbook: 04-certificate-authority.yml
- import_playbook: additional-tasks/04-1-copy-certs.yml

# generate Kubernetes Configuration Files for Authentification
- import_playbook: 05-kubernetes-configuration-files.yml
- import_playbook: additional-tasks/05-1-copy-config-files.yml

# generate encryption file
- import_playbook: 06-data-encryption-keys.yml
- import_playbook: additional-tasks/06-1-copy-encryption-data.yml

# bootstrap etcd cluster
- import_playbook: 07-bootstrapping-etcd.yml

# bootstrap kubernetes control plane
- import_playbook: 08-bootstrapping-kubernetes-controllers.yml
- import_playbook: additional-tasks/08-1-frontend-load-balancer.yml

# bootstrap kubernetes worker nodes 
- import_playbook: 09-bootstrapping-kubernetes-workers.yml

# configure kubectl
- import_playbook: 10-configuring-kubectl.yml

# provision pod network routes
- import_playbook: 11-pod-network-routes.yml

# deploy dns cluster add-on
- import_playbook: 12-dns-addon.yml

# smoke test
- import_playbook: 13-smoke-test.yml
