---
- name: 04-generate Kubernetes API server certificate and private key
  shell: cfssl gencert \
         -ca=ca.pem \
         -ca-key=ca-key.pem \
         -config=ca-config.json \
         -hostname=10.32.0.1,{{ hostvars['controller-0']['gce_private_ip'] }},{{ hostvars['controller-1']['gce_private_ip'] }},{{ hostvars['controller-2']['gce_private_ip'] }},{{ gce_lb_public_ip }},127.0.0.1,kubernetes.default \
         -profile=kubernetes \
         kubernetes-csr.json | cfssljson -bare kubernetes
  args:
    chdir: /opt/kubernetes-pki  

- name: 04-generate service account certificate and private key
  shell: cfssl gencert \
         -ca=ca.pem \
         -ca-key=ca-key.pem \
         -config=ca-config.json \
         -profile=kubernetes \
         service-account-csr.json | cfssljson -bare service-account
  args:
    chdir: /opt/kubernetes-pki

