---
- name: Generate CA keys
  shell: cfssl gencert -initca ca-csr.json | cfssljson -bare ca
  args:
    chdir: /opt/kubernetes-pki

- name: Generate Admin Client Certificate
  shell: cfssl gencert \
         -ca=ca.pem \
         -ca-key=ca-key.pem \
         -config=ca-config.json \
         -profile=kubernetes \
         admin-csr.json | cfssljson -bare admin
  args:
    chdir: /opt/kubernetes-pki

- name: Generate certificates for each worker node 
  shell: cfssl gencert \
         -ca=ca.pem \
         -ca-key=ca-key.pem \
         -config=ca-config.json \
         -hostname="{{ item }},{{ hostvars[item]['gce_public_ip'] }},{{ hostvars[item]['gce_private_ip'] }}" \
         -profile=kubernetes \
         {{ item }}-csr.json | cfssljson -bare {{ item }}
  args:
    chdir: /opt/kubernetes-pki
  with_items:
    - worker-0
    - worker-1
    - worker-2

- name: Generate certificate for Controller Manager
  shell: cfssl gencert \
         -ca=ca.pem \
         -ca-key=ca-key.pem \
         -config=ca-config.json \
         -profile=kubernetes \
         kube-controller-manager-csr.json | cfssljson -bare kube-controller-manager
  args:
    chdir: /opt/kubernetes-pki

- name: Generate certificate for kube proxy client
  shell: cfssl gencert \
         -ca=ca.pem \
         -ca-key=ca-key.pem \
         -config=ca-config.json \
         -profile=kubernetes \
         kube-proxy-csr.json | cfssljson -bare kube-proxy
  args:
    chdir: /opt/kubernetes-pki

- name: Generate Scheduler CLient Certificate
  shell: cfssl gencert \
         -ca=ca.pem \
         -ca-key=ca-key.pem \
         -config=ca-config.json \
         -profile=kubernetes \
         kube-scheduler-csr.json | cfssljson -bare kube-scheduler
  args:
    chdir: /opt/kubernetes-pki
