---
- name: 06-generate an encryption key 
  shell: head -c 32 /dev/urandom | base64
  register: encryption_key

- name: 06-Create encryption config file
  become: yes
  template:
    src: encryption-config.yaml
    dest: /opt/kubernetes-pki/encryption-config.yaml
  when: encryption_key.changed
