---
- name: generate an encryption key 
  shell: head -c 32 /dev/urandom | base64
  register: encryption_key

- name: Ensure the encryption config file is present
  become: yes
  template:
    src: encryption-config.yaml
    dest: /opt/kubernetes-pki/encryption-config.yaml
  when: encryption_key.changed
