---
- name: 04-1 Ensure /opt/kubernetes-pki present on all hosts
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: ensure destination directory exists
      file:
        path: "/opt/kubernetes-pki"
        state: directory

- name: 04-1 Change permissions on localhost
  hosts: localhost
  become: yes
  gather_facts: no
  tasks:
    - name: Change permissions on localhost
      file:
        path: "/opt/kubernetes-pki/{{ item }}"
        mode: 0644
      with_items:
        - admin-key.pem
        - ca-key.pem
        - kube-controller-manager-key.pem
        - kube-proxy-key.pem
        - kubernetes-key.pem
        - kube-scheduler-key.pem
        - service-account-key.pem
        - worker-0-key.pem
        - worker-1-key.pem
        - worker-2-key.pem
        
- name: 04-1 Copy certificates to workers
  hosts: tag_worker
  tasks:
    - name: Copy certificates to workers
      copy:
        src: "/opt/kubernetes-pki/{{ item }}"
        dest: "/home/k8s/{{ item }}"
      with_items:
        - "ca.pem"
        - "{{ ansible_hostname }}-key.pem"
        - "{{ ansible_hostname }}.pem"

- name: 04-1 Copy certificates to controllers 
  hosts: tag_controller
  gather_facts: no
  tasks:
    - name: Copy certificates to controllers
      copy:
        src: "/opt/kubernetes-pki/{{ item }}"
        dest: "/home/k8s/{{ item }}"
      with_items:
        - ca.pem
        - ca-key.pem
        - kubernetes-key.pem
        - kubernetes.pem
        - service-account-key.pem
        - service-account.pem
