---
- name: 05-1 Ensure permissions are correct
  hosts: localhost
  gather_facts: no
  become: yes
  tasks:
    - name: Set permissions to kubeconfig files
      file:
        path: "/opt/kubernetes-pki/{{ item }}"
        mode: 0644
      with_items:
        - admin.kubeconfig
        - kube-controller-manager.kubeconfig
        - kube-proxy.kubeconfig
        - kube-scheduler.kubeconfig
        - worker-0.kubeconfig
        - worker-1.kubeconfig
        - worker-2.kubeconfig

- name: 05-1 Copy certificates to workers
  hosts: tag_worker
  gather_facts: yes
  tasks:
    - name: Copy certificates to workers
      copy:
        src: "/opt/kubernetes-pki/{{ item }}"
        dest: "/home/k8s/{{ item }}"
      with_items:
        - "{{ ansible_hostname }}.kubeconfig"
        - kube-proxy.kubeconfig

- name: 05-1 Copy certificates to controllers 
  hosts: tag_controller
  gather_facts: no
  tasks:
    - name: Copy certificates to controllers
      copy:
        src: "/opt/kubernetes-pki/{{ item }}"
        dest: "/home/k8s/{{ item }}"
      with_items:
        - admin.kubeconfig
        - kube-controller-manager.kubeconfig
        - kube-scheduler.kubeconfig
