---
- name: Copy certificates to workers
  hosts: tag_worker
  gather_facts: yes
  tasks:
    - name: Copy certificates to workers
      copy:
        src: "/opt/kubernetes-pki/{{ item }}"
        dest: "/home/k8s/{{ item }}"
      with_items:
        - "{{ ansible_hostname }}.kubeconfig"
        - kube-proxy.kubeconfig

- name: Copy certificates to controllers 
  hosts: tag_controller
  gather_facts: yes
  tasks:
    - name: Copy certificates to workers
      copy:
        src: "/opt/kubernetes-pki/{{ item }}"
        dest: "/home/k8s/{{ item }}"
      with_items:
        - admin.kubeconfig
        - kube-controller-manager.kubeconfig
        - kube-scheduler.kubeconfig
