---
- name: Copy certificates to controllers 
  hosts: tag_controller
  gather_facts: no
  become: yes
  tasks:
    - name: Copy certificates to controllers 
      copy:
        src: /opt/kubernetes-pki/encryption-config.yaml
        dest: /home/k8s/encryption-config.yaml
