---
- name: Copy certificates to controllers 
  hosts: controllers-pki
  gather_facts: yes
  tasks:
    - name: Copy certificates to controllers 
      copy:
        src: /opt/kubernetes-pki/encryption-config.yaml
        dest: /home/k8s/encryption-config.yaml
