- name: 03-Create Kubernetes controllers
  gce:
    instance_names: "controller-{{ item }}" 
    project_id: "{{ project_id }}"
    state: present
    machine_type: n1-standard-1
    disk_size: 200
    image: ubuntu-18 
    zone: europe-west1-b
    ip_forward: yes
    service_account_permissions:
      - compute-rw
      - storage-ro
      - service-management
      - service-control
      - logging-write
      - monitoring
    network: kubernetes-the-hard-way
    subnetwork: kubernetes
    tags: 
      - kubernetes-the-hard-way
      - controller
  with_items:
    - 0
    - 1
    - 2
  tags: controllers_create

- name: 03-Create Kubernetes workers
  gce:
    instance_names: "worker-{{ item }}" 
    project_id: "{{ project_id }}"
    state: present
    machine_type: n1-standard-1
    disk_size: 200
    image: ubuntu-18 
    zone: europe-west1-b
    ip_forward: yes
    service_account_permissions:
      - compute-rw
      - storage-ro
      - service-management
      - service-control
      - logging-write
      - monitoring
    network: kubernetes-the-hard-way
    subnetwork: kubernetes
    metadata: '{"sshKeys":"k8s:{{ lookup("file", "./ssh/k8s_key.pub") }}","pod-cidr":"10.200.{{ item }}.0/24"}'
    tags: 
      - kubernetes-the-hard-way
      - worker
  with_items:
    - 0
    - 1
    - 2
  tags: workers_create

