---
- name: 03-Create custom VPC network
# auto_create_subnetwork option creates legacy network instead custom hence using gce_net module at the moment - bug report #45803
#  gcp_compute_network:
#    name: kubernetes-the-hard-way
#    project: docker-221205
#    auto_create_subnetworks: no
#  register: kuber_network
  gce_net:
    name: kubernetes-the-hard-way
    project_id: "{{ project_id }}"
    mode: custom
    ipv4_range: 10.240.0.0/24
    subnet_name: kubernetes
    subnet_region: europe-west1
  register: kuber_network
  tags: new_net

#- name: Create subnetwork
#  gcp_compute_subnetwork:
#    ip_cidr_range: 10.240.0.0/24
#    name: kubernetes
#    network: "{{ kuber_network }}"
#    region: europe-west1
#    project: docker-221205
#  register: kuber_subnetwork
#  tags: new_net

#- name: show kuber subnetwork
#  debug:
#    msg: "{{ kuber_subnetwork }}"
#  tags: new_net

- name: 03-Create Firewall Rule for internal communication
  gcp_compute_firewall:
    network: "projects/{{ project_id }}/global/networks/kubernetes-the-hard-way" 
    name: kubernetes-the-hard-way-allow-internal
    source_ranges: 
      - '10.240.0.0/24'
      - '10.200.0.0/16'
    allowed: 
      - ip_protocol: tcp 
      - ip_protocol: udp
      - ip_protocol: icmp
    project: "{{ project_id }}"

- name: 03-Add another firewall rule
  gcp_compute_firewall:
    network: "projects/{{ project_id }}/global/networks/kubernetes-the-hard-way" 
    name: kubernetes-the-hard-way-allow-external
    source_ranges: '0.0.0.0/0'
    allowed: 
      - ip_protocol: tcp 
        ports:
          - '22'
          - '6443'
      - ip_protocol: icmp
    project: "{{ project_id }}"

- name: 03-Allocate a static IP address for external load balancer
  gcp_compute_address:
    name: kubernetes-the-hard-way
    region: europe-west1
    project: "{{ project_id }}"
  register: gce_eip
