---
- name: 05-Ensure directory for config files is present on localhost
  file:
    path: /opt/kubernetes-pki
    state: directory
    mode: 0755

- include: gencert-worker.yml
- include: gencert-controller.yml

